---
logging:
  level:
    root: WARN

spring:
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always
  profiles:
    default: development

server:
  address: 0.0.0.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
